language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 2.0.0
os:
  - linux
branches:
  only:
    - master
before_script:
  - chmod a+x ./build.sh
script:
  - "./build.sh --publish"
before_deploy:
  - openssl aes-256-cbc -K $encrypted_0f88257bce16_key -iv $encrypted_0f88257bce16_iv - in id_rsa.enc -out /tmp/id_rsa -d
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/artifacts/ $SSH_LOGIN_USERNAME@$SSH_REMOTE_HOST:/var/WebApps/Test
  on:
    branch: master

